name: Build and Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
       fail-fast: false
       matrix:
         os: [ubuntu-latest]
         py: ["3.7", "3.8", "3.9", "3.10"]
         include:
           - os: macos-latest
             python-version: "3.10"
           - os: windows-latest
             python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade build tools
      run: pip install --upgrade pip build wheel setuptools
    - name: Build distributions
      run: python -m build
    - name: Test with Pytest
      run: pytest
